In [3]:
import pandas as pd
from sklearn.linear_model import SGDRegressor
import boto3
from io import StringIO

In [4]:
session = boto3.Session(profile_name='ai-dataset-bucket-readwrite-795524854110')

# Connect to S3
s3 = session.client('s3')

bucket_name = 'artificial-intelligence-datasets'
object_key = 'prepared/NIFTY50 Dataset/NIFTY50_prepared.csv'  # e.g., 'project1/data/sample.csv'

# Download object into memory
response = s3.get_object(Bucket=bucket_name, Key=object_key)

with response['Body'] as stream:
    body = stream.read().decode('utf-8')

df = pd.read_csv(StringIO(body))

df.head()

,Date,Symbol,Close,Symbol_en,Prev_Close_scaled,Open_scaled,High_scaled,Low_scaled,Last_scaled,VWAP_scaled,Volume_scaled,Turnover_scaled,Trades_scaled,DeliverableVolume_scaled,Symbol_en_scaled,Year,Month,Day,Day_of_Week,Day_of_Year
0,2007-11-27,MUNDRAPORT,962.90,483791.136313,-0.130695,0.209617,0.481037,0.224253,0.404750,0.431607,9.384118,15.385090,-0.039056,7.229856,7.441885,2007,11,27,1,331
1,2007-11-28,MUNDRAPORT,893.90,478060.423240,0.409546,0.430620,0.420031,0.333491,0.328343,0.386832,1.274760,2.131802,-0.039056,0.712739,7.255762,2007,11,28,2,332
2,2007-11-29,MUNDRAPORT,884.20,477708.343281,0.338258,0.353166,0.343518,0.298829,0.330408,0.331779,1.468552,2.271529,-0.039056,0.415349,7.244327,2007,11,29,3,333
3,2007-11-30,MUNDRAPORT,921.55,478060.423240,0.328236,0.333544,0.387494,0.350297,0.373774,0.374218,1.284908,2.114470,-0.039056,0.563606,7.255762,2007,11,30,4,334
4,2007-12-03,MUNDRAPORT,969.30,484680.351304,0.366825,0.384922,0.425114,0.383908,0.426433,0.411905,0.702122,1.287443,-0.039056,0.218777,7.470765,2007,12,3,0,337